name: Super Linter 🧹

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  super-linter:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Super-Linter
        uses: github/super-linter@v4.10.1
        env:
          VALIDATE_JAVA: true
